version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - my-network

networks:
  my-network:
